/vis/scene/create
/vis/drawVolume worlds
/vis/scene/add/volume
/vis/sceneHandler/attach
/vis/scene/add/axes 0 0 0 100 cm # Add axis (has to be after /vis/scene/create )


/vis/viewer/flush # Draw a picture that has just the detector (no trajectories or hits).
/vis/scene/add/trajectories rich # Declare that trajectories and hits should be added to the scene
/vis/scene/add/hits

/vis/viewer/reset
/vis/viewer/set/viewpointThetaPhi 90. 0. # Specify view angle:

/vis/viewer/set/style surface

/vis/viewer/set/viewpointThetaPhi 90 180 deg
/vis/viewer/zoom 3.0
/vis/viewer/set/lightsThetaPhi 40 50
/vis/viewer/addCutawayPlane 0.0 0.0 0.0 m 1.0 0.0 0.0
/vis/viewer/set/targetPoint 0 0 6000 mm

/vis/scene/endOfEventAction accumulate
/vis/scene/endOfRunAction refresh

