/compton/setgeofile geometry/compton/ComptonGeometry.gdml
/compton/parallel/setfile geometry/compton/ComptonParallel.gdml


#/physics_lists/em/SyncRadiationAll true
/compton/physlist/optical/enable
/compton/physlist/parallel/enable
/compton/physlist/synchrotron/enable

/run/initialize
/compton/printgeometry false
/run/verbose 0
#/tracking/verbose 3

/compton/addfield map_directory/dipole_magnetic_field_20_1.txt
/compton/addfield map_directory/dipole_magnetic_field_20_2.txt
/compton/addfield map_directory/dipole_magnetic_field_20_3.txt
/compton/addfield map_directory/dipole_magnetic_field_20_4.txt


/compton/evgen/beam/origin 0  215.49 -9849.76 mm
/compton/evgen/beam/xspread 0 um
/compton/evgen/beam/yspread 0 um
/compton/evgen/beam/rasx 0 um
/compton/evgen/beam/rasy 0 um

/compton/beamene 11.0 GeV
/compton/beamcurr 65 microampere


/compton/evgen/set beam

/compton/evgen/beamPolarization +L
/compton/field/equationtype 2
/compton/field/steppertype 2

#/compton/evgen/set laser
#/compton/evgen/laser/origin 0  215.49 0 mm
#/compton/evgen/laser/energy 1 MeV


/compton/SD/disable_all
/compton/SD/enable 81
/compton/SD/detect lowenergyneutral 81
/compton/SD/detect secondaries 81

/process/list

/compton/seed 42
/compton/interval 1000000

/run/beamOn 8000

