/compton/geometry/setfile geometry/compton/ComptonGeometry.gdml
/compton/parallel/setfile geometry/compton/ComptonParallel.gdml


/compton/physlist/synchrotron/enable

/run/verbose 0
#/tracking/verbose 1
#///stepping/verbose 1

/compton/field/add 1 map_directory/20/dipole_magnetic_field_20_1.txt
/compton/field/add 2 map_directory/20/dipole_magnetic_field_20_2.txt
/compton/field/add 3 map_directory/20/dipole_magnetic_field_20_3.txt
/compton/field/add 4 map_directory/20/dipole_magnetic_field_20_4.txt

/run/initialize

/compton/geometry/relative_position gate_valve_phy (40,40.0,0.0)

/compton/printgeometry 1


#/compton/evgen/set compton

#/compton/step/killpidafterz 22 5000

/compton/evgen/set beam
/compton/evgen/beam/origin 0 215.49 -9849.76 mm
/compton/evgen/beam/beamene 11.0 GeV
/compton/evgen/beam/beamcurr 65 microampere
/compton/evgen/beam/originspread 30 30 0 um
/compton/evgen/beam/direction 0 0.0000 1


#/compton/evgen/set laser
#/compton/evgen/laser/origin 0  215.49 0 mm
#/compton/evgen/laser/energy 1 MeV


/compton/SD/disable_all
/compton/SD/enable 41
/compton/SD/detect lowenergyneutral 41
/compton/SD/detect secondaries 41
/compton/SD/detect boundaryhits 41


/compton/seed 42
/compton/interval 10

/compton/filename /tmp/f_20_gagain.root

/run/beamOn 2

