# Use this open statement to create an OpenGL view:
/control/macroPath macros
/vis/open OGL 600x600-0+0

# This is the current working geometry
/compton/geometry/setfile geometry/compton/ComptonGeometry.gdml
/compton/parallel/setfile geometry/compton/ComptonParallel.gdml

#/physics_lists/em/SyncRadiationAll true
#///compton/physlist/optical/enable
#/compton/setphysicslist beam
/compton/physlist/synchrotron/enable

/compton/field/add 1 map_directory/20/dipole_magnetic_field_20_1.txt
/compton/field/add 2 map_directory/20/dipole_magnetic_field_20_2.txt
/compton/field/add 3 map_directory/20/dipole_magnetic_field_20_3.txt
/compton/field/add 4 map_directory/20/dipole_magnetic_field_20_4.txt
/compton/field/globalscale 0.97886

/run/initialize
/compton/printgeometry false

/control/execute vis/vis.mac

#/vis/scene/add/magneticField 10



/compton/evgen/set beam
/compton/evgen/beam/origin 0 215.49 -9849.76 mm
/compton/evgen/beam/beamene 11.0 GeV
/compton/evgen/beam/beamcurr 65 microampere
/compton/evgen/beam/rasx 0 um
/compton/evgen/beam/rasy 0 um
/compton/evgen/beam/xspread 0 um
/compton/evgen/beam/yspread 0 um
/compton/evgen/beam/direction 0 0.0000 1
#
#
#
##/compton/step/killminenergy 1 MeV
/compton/step/killpidafterz 11 5000
#
#/compton/SD/disable_all
/compton/SD/enable 41
/compton/SD/detect lowenergyneutral 41
/compton/SD/detect secondaries 41
/compton/SD/detect boundaryhits 41
/compton/SD/enable 13
/compton/SD/detect lowenergyneutral 13
/compton/SD/detect secondaries 13
/compton/SD/detect boundaryhits 13
/compton/SD/enable 14
/compton/SD/detect lowenergyneutral 14
/compton/SD/detect secondaries 14
/compton/SD/detect boundaryhits 14
/compton/SD/enable 15
/compton/SD/detect lowenergyneutral 15
/compton/SD/detect secondaries 15
/compton/SD/detect boundaryhits 15
/compton/SD/enable 16
/compton/SD/detect lowenergyneutral 16
/compton/SD/detect secondaries 16
/compton/SD/detect boundaryhits 16


/compton/filename comptonout2.root
/compton/seed 42

/run/beamOn 2

/vis/enable
/vis/viewer/flush


