/compton/setgeofile geometries/test/ComptonGeometry.gdml
/compton/parallel/setfile geometries/test/ComptonParallel.gdml

/compton/physlist/parallel/enable
/physics_lists/em/SyncRadiation true

/run/initialize
/compton/printgeometry false
/run/verbose 0
#/tracking/verbose 3

/compton/addfield map_directory/dipole_magnetic_field_1_13.txt
#/compton/addfield map_directory/dipole_magnetic_field_2_12.txt
#/compton/addfield map_directory/dipole_magnetic_field_3_12.txt
#/compton/addfield map_directory/dipole_magnetic_field_4_12.txt

/compton/evgen/beam/origin 0  215.49 -8249.76 mm
#/compton/evgen/beam/xspread 60 um
#/compton/evgen/beam/yspread 60 um
/compton/evgen/beam/rasx 0 um
/compton/evgen/beam/rasy 0 um
/compton/evgen/beam/corrx 0
/compton/evgen/beam/corry 0


/compton/beamene 110.0 GeV
/compton/beamcurr 65 microampere


/compton/evgen/set beam

/compton/evgen/beamPolarization +L
/compton/field/equationtype 2
/compton/field/steppertype 2


/compton/SD/disable_all
/compton/SD/enable 25
#/compton/SD/detect secondaries 25
/compton/SD/detect boundaryhits 25
#/compton/SD/detect incomingonly 25

/process/list

/compton/seed 42
/compton/filename output/inc_bdry_only_more_25.root

/run/beamOn 50000

